<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KabupatenKota_cityAndProvince</name>
   <tag></tag>
   <elementGuidId>2a7e08a6-6700-4516-a769-16d347c96058</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cityAndProvince']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cityAndProvince</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7343ab6-b7cf-406e-947e-91c1025864c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bba60665-260a-4a97-aeaf-22717f6d3717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>autocomplete__field_vc5UL</value>
      <webElementGuid>3fc07f7c-739d-4cdd-917b-319f8e3b176d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cityAndProvince</value>
      <webElementGuid>c2469bb8-c03b-4e03-aa12-e550361caff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cityAndProvince</value>
      <webElementGuid>2f571452-6e66-4508-b656-b87644920b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Kabupaten/Kota</value>
      <webElementGuid>b61ac996-ece0-408d-8ddc-a0b61ca1484c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b01e5575-50f9-4291-a4d4-97b5de9b7046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cityAndProvince&quot;)</value>
      <webElementGuid>c6165aac-7b09-4f14-9c4e-b21ab3bbb14d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cityAndProvince']</value>
      <webElementGuid>0392c199-7216-4608-bd57-888bbceaa7ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='safe-area']/div[2]/div[2]/div/div[7]/div/input</value>
      <webElementGuid>0ab83325-d73b-42a1-af54-bc7965446f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>9ae52c68-e46d-4f32-9627-d4420580ad49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cityAndProvince' and @name = 'cityAndProvince' and @placeholder = 'Pilih Kabupaten/Kota' and @type = 'text']</value>
      <webElementGuid>835f59e1-bd6b-4e5f-a478-76d824df6b07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
